In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import ast

In [2]:
sequence_length = 50
n_mfcc = 20

In [3]:
def extract_mfccs(path):
    df = pd.read_csv(path)
    x = []
    ids = df["speaker_id"]
    mfccs = df["mfcc"]
    x = []
    y = np.array([])
    for i in range(len(mfccs)):
        mfcc = mfccs.apply(ast.literal_eval).to_numpy()[i]
        mfcc /= np.max(mfcc)
        for j in range(0, len(mfcc), sequence_length):
            sampleX = np.array(mfcc[j: j + sequence_length])
            try:
                sampleX.reshape(sequence_length, n_mfcc)
                x.append(sampleX)
                y = np.append(y, ids[i])
            except:
                continue

    x = tf.reshape(x, shape=[-1, sequence_length, n_mfcc])
    return [x, y]

x, y = extract_mfccs("samples_dataset.csv")
x.shape

TensorShape([1566, 50, 20])

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(64, return_sequences=True, input_shape=(sequence_length, n_mfcc)),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x, y, epochs=10, batch_size=32)



Epoch 1/10


49/49 [==============================] - 4s 21ms/step - loss: 0.4412 - accuracy: 0.7778
Epoch 2/10
49/49 [==============================] - 1s 21ms/step - loss: 0.1218 - accuracy: 0.9674
Epoch 3/10
49/49 [==============================] - 1s 21ms/step - loss: 0.0563 - accuracy: 0.9847
Epoch 4/10
49/49 [==============================] - 1s 20ms/step - loss: 0.0479 - accuracy: 0.9853
Epoch 5/10
49/49 [==============================] - 1s 21ms/step - loss: 0.0445 - accuracy: 0.9866
Epoch 6/10
49/49 [==============================] - 1s 21ms/step - loss: 0.0247 - accuracy: 0.9923
Epoch 7/10
49/49 [==============================] - 1s 21ms/step - loss: 0.0286 - accuracy: 0.9917
Epoch 8/10
49/49 [==============================] - 1s 20ms/step - loss: 0.0364 - accuracy: 0.9898
Epoch 9/10
49/49 [==============================] - 1s 21ms/step - loss: 0.0729 - accuracy: 0.9745
Epoch 10/10
49/49 [==============================] - 1s 21ms/step - loss: 0.0235 - accuracy: 0.9936


In [5]:
x, y = extract_mfccs("tests_dataset.csv")
model.evaluate(x, y)

13/13 [==============================] - 1s 8ms/step - loss: 0.3088 - accuracy: 0.9351


[0.3088153302669525, 0.9350649118423462]

In [6]:
output = model.predict(x)
list(zip(output, y))

13/13 [==============================] - 1s 7ms/step


[(array([0.00132099], dtype=float32), 0.0),
 (array([0.00935107], dtype=float32), 0.0),
 (array([0.00967266], dtype=float32), 0.0),
 (array([0.00327144], dtype=float32), 0.0),
 (array([0.00129595], dtype=float32), 0.0),
 (array([0.00576712], dtype=float32), 0.0),
 (array([0.0011308], dtype=float32), 0.0),
 (array([0.00114575], dtype=float32), 0.0),
 (array([0.00189447], dtype=float32), 0.0),
 (array([0.00106346], dtype=float32), 0.0),
 (array([0.00181819], dtype=float32), 0.0),
 (array([0.00163828], dtype=float32), 0.0),
 (array([0.00114968], dtype=float32), 0.0),
 (array([0.00121274], dtype=float32), 0.0),
 (array([0.00112716], dtype=float32), 0.0),
 (array([0.00111011], dtype=float32), 0.0),
 (array([0.00176628], dtype=float32), 0.0),
 (array([0.00121741], dtype=float32), 0.0),
 (array([0.00114272], dtype=float32), 0.0),
 (array([0.00109281], dtype=float32), 0.0),
 (array([0.00118624], dtype=float32), 0.0),
 (array([0.001234], dtype=float32), 0.0),
 (array([0.00125411], dtype=float32